def return_json():
  return {
    "pagination": {
      "limit": 100,
      "offset": 0,
      "count": 10,
      "total": 13163
    },
    "data": [
      {
        "id": "5939517",
        "fleet_average_age": "10.9",
        "airline_id": "1",
        "callsign": "AMERICAN",
        "hub_code": "DFW",
        "iata_code": "AA",
        "icao_code": "AAL",
        "country_iso2": "US",
        "date_founded": "1934",
        "iata_prefix_accounting": "1",
        "airline_name": "American Airlines",
        "country_name": "United States",
        "fleet_size": "963",
        "status": "active",
        "type": "scheduled"
      },
      {
        "id": "5939518",
        "fleet_average_age": "17",
        "airline_id": "2",
        "callsign": "DELTA",
        "hub_code": "ATL",
        "iata_code": "DL",
        "icao_code": "DAL",
        "country_iso2": "US",
        "date_founded": "1928",
        "iata_prefix_accounting": "6",
        "airline_name": "Delta Air Lines",
        "country_name": "United States",
        "fleet_size": "823",
        "status": "active",
        "type": "scheduled"
      },
      {
        "id": "5939519",
        "fleet_average_age": "13.8",
        "airline_id": "3",
        "callsign": "UNITED",
        "hub_code": "ORD",
        "iata_code": "UA",
        "icao_code": "UAL",
        "country_iso2": "US",
        "date_founded": "1931",
        "iata_prefix_accounting": "16",
        "airline_name": "United Airlines",
        "country_name": "United States",
        "fleet_size": "715",
        "status": "active",
        "type": "scheduled"
      },
      {
        "id": "5939520",
        "fleet_average_age": "12.3",
        "airline_id": "4",
        "callsign": "SOUTHWEST",
        "hub_code": "DAL",
        "iata_code": "WN",
        "icao_code": "SWA",
        "country_iso2": "US",
        "date_founded": "1967",
        "iata_prefix_accounting": "526",
        "airline_name": "Southwest Airlines",
        "country_name": "United States",
        "fleet_size": "712",
        "status": "active",
        "type": "scheduled"
      },
      {
        "id": "5939521",
        "fleet_average_age": "6.9",
        "airline_id": "5",
        "callsign": "CHINA SOUTHERN",
        "hub_code": "CAN",
        "iata_code": "CZ",
        "icao_code": "CSN",
        "country_iso2": "CN",
        "date_founded": "2004",
        "iata_prefix_accounting": "784",
        "airline_name": "China Southern Airlines",
        "country_name": "China",
        "fleet_size": "498",
        "status": "active",
        "type": "scheduled"
      },
      {
        "id": "5939522",
        "fleet_average_age": "8.4",
        "airline_id": "6",
        "callsign": "CHINA EASTERN",
        "hub_code": "PVG",
        "iata_code": "MU",
        "icao_code": "CES",
        "country_iso2": "CN",
        "date_founded": "1988",
        "iata_prefix_accounting": "781",
        "airline_name": "China Eastern Airlines",
        "country_name": "China",
        "fleet_size": "407",
        "status": "active",
        "type": "scheduled"
      },
      {
        "id": "5939523",
        "fleet_average_age": "11.1",
        "airline_id": "7",
        "callsign": "RYANAIR",
        "hub_code": "STN",
        "iata_code": "FR",
        "icao_code": "RYR",
        "country_iso2": "IE",
        "date_founded": "1985",
        "iata_prefix_accounting": "224",
        "airline_name": "Ryanair",
        "country_name": "Ireland",
        "fleet_size": "353",
        "status": "active",
        "type": "scheduled"
      },
      {
        "id": "5939524",
        "fleet_average_age": "21.9",
        "airline_id": "8",
        "callsign": "FEDEX",
        "hub_code": "MEM",
        "iata_code": "FX",
        "icao_code": "FDX",
        "country_iso2": "US",
        "date_founded": "1971",
        "iata_prefix_accounting": "23",
        "airline_name": "FedEx Express",
        "country_name": "United States",
        "fleet_size": "367",
        "status": "active",
        "type": "cargo"
      },
      {
        "id": "5939525",
        "fleet_average_age": "6.3",
        "airline_id": "9",
        "callsign": "TURKISH",
        "hub_code": "IST",
        "iata_code": "TK",
        "icao_code": "THY",
        "country_iso2": "TR",
        "date_founded": "1933",
        "iata_prefix_accounting": "235",
        "airline_name": "Turkish Airlines",
        "country_name": "Turkey",
        "fleet_size": "285",
        "status": "active",
        "type": "scheduled"
      },
      {
        "id": "5939526",
        "fleet_average_age": "11.7",
        "airline_id": "10",
        "callsign": "AIRFRANS",
        "hub_code": "CDG",
        "iata_code": "AF",
        "icao_code": "AFR",
        "country_iso2": "FR",
        "date_founded": "1933",
        "iata_prefix_accounting": "57",
        "airline_name": "Air France",
        "country_name": "France",
        "fleet_size": "226",
        "status": "active",
        "type": "scheduled"
      }
    ]
  }